### ISSUE TITLE
Arreglar error con la imagen de Docker

### ISSUE THREAD

**Issue by bae1001** [bae1001/eLearningQA#14]
La página desplegada desde Docker  no funciona bien.

**Comment by bae1001** [comment]
Aparentemente, al construir el war hay ciertos archivos que no se añaden o no se encuentran en el war, los archivos que no encuentra en este caso son los situados en la carpeta configurations, de ahi recibo un null en la linea 15 de login.jsp. Comentando la linea mencionada recibo otro null en otro punto del codigo por lo que este problema debe ser de las capas del war. He probado varias cosas que he ido encontrando por varias documentaciones sin éxito. El war ejecutado desde mi terminal local funciona sin problemas, pero al ser ejecutado en Docker me da este problema, esto puede ser clave para entender lo que sucede.

**Comment by bae1001** [comment]
He encontrado la razón por la que falla esto, y es debido a que en la aplicación al utilizar recursos se utilizan las rutas exactas en del proyecto, esto siginifica que el war ejecutado desde fuera del proyecto dará error siempre por que no tiene acceso a los ficheros que se utilizan en el código, devolviendo null en las llamadas. Por lo que el problema no es realmente de Dokcer, si no del war en sí. Desempaquetando el war he podido ver que no contiene los archivos que se necesitan o no están correctamente definidos en el classpath, por lo que habrá que pensar en las formas empaquetar y declarar correctamente las rutas de los ficheros.

**Comment by clopezno** [comment]
Creo que has podido dar con la clave de este problema de despliegue.
La solución es utilizar los recursos de Java https://docs.oracle.com/javase/8/docs/technotes/guides/lang/resources.html.
