### ISSUE TITLE
Programar

### ISSUE THREAD

**Issue by bae1001** [bae1001/eLearningQA#28]
Esta regla consiste en hacer una comparación entre los participantes de tipo estudiante de una asignatura y los participantes de los cuestionarios creados que deben completar. De esta comparación podremos sacar un índice que nos permitirá visualizar la efectividad o alcance que están teniendo los cuestionarios creados.

**Comment by clopezno** [comment]
@bae1001 ¿puedes añadir una descripción textual de la regla en el campo descripción de la issue? Puede  ayudar a comprender mejor la regla engagement.

**Comment by bae1001** [comment]
> @bae1001 ¿puedes añadir una descripción textual de la regla en el campo descripción de la issue? Puede ayudar a comprender mejor la regla engagement.

Si, por supuesto.
