### ISSUE TITLE
Nuevas reglas de evaluación sobre cuestionarios

### ISSUE THREAD

**Issue by clopezno** [bae1001/eLearningQA#53]
Propongo nuevas posibles reglas de diseño:

- Regla de diseño - ¿El cuestionario y las preguntas tienen definida retroalimentación? 
- Regla de diseño - ¿Las preguntas de ensayo tienen definida una guía de evaluación para los profesores"
- Regla de evaluación - ¿Los estudiantes consultan la retroalimentación del cuestionario en caso de que este abierta? 

Valorar si se pueden implementar o documentarlas en líneas futuras de trabajo

**Comment by bae1001** [comment]
Se han añadido las reglas a lineas futuras de trabajo
