### ISSUE TITLE
Memo -  conclusiones - experiencias de usuarios

### ISSUE THREAD

**Issue by clopezno** [bae1001/eLearningQA#54]
Documentar en la sección de conclusiones que la aplicación ha sido probada con cursos reales de Moodle y ha ayudado a los profesores ha identificar y analizar problemas en los cuestionarios.  En concreto en la asignatura de Desarrollo Avanzado de Software del 4º Curso de Ingeniería Informática en la modalidad online, el profesor ha identificado en la fase de realización, una baja participación en los cuestionarios de autoevaluación a pesar que los índices de facilidad son altos (comprendidos entre 69% y 88%).

Puede ser interesante añadir la experiencia de usuario de  @rmartico

**Comment by bae1001** [comment]
Se ha añadido el texto a conclusiones
